//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleManagementSystem.Models
{
    using System;

    public partial class Quotation
    {
        public int Id { get; set; }
        /// <summary>
        /// This is a foreign key reference to id in visitor table
        /// </summary>
        public Nullable<int> VisitorId { get; set; }
        /// <summary>
        /// This is a foreign key reference to the id in vehicle table
        /// </summary>
        public Nullable<int> VehicleId { get; set; }
    
        public virtual Vehicle Vehicle { get; set; }
        public virtual Visitor Visitor { get; set; }
    }
}
