//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleManagementSystem.Models
{
    using System;

    public partial class Sale
    {
        public int Id { get; set; }
        /// <summary>
        /// Foreign key which references the id in vehicle table
        /// </summary>
        public Nullable<int> VehicleId { get; set; }
        /// <summary>
        /// Foreign key which references the userid in user table
        /// </summary>
        public Nullable<int> UserId { get; set; }
        /// <summary>
        /// This is a date on which sale was done
        /// </summary>
        public Nullable<System.DateTime> DateOfPurchase { get; set; }
    
        public virtual User User { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
