//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleManagementSystem.Models
{
    using System;

    public partial class UserRoleMapping
    {
        public int Id { get; set; }
        /// <summary>
        /// this is a foreign key that references the id in the user table
        /// </summary>
        public Nullable<int> UserId { get; set; }
        /// <summary>
        /// This is a foreign key that references the id in the role table
        /// </summary>
        public Nullable<int> RoleId { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual User User { get; set; }
    }
}
