//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleManagementSystem.Models
{
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Sales = new HashSet<Sale>();
            this.UserRoleMappings = new HashSet<UserRoleMapping>();
        }
    
        public int Id { get; set; }
        /// <summary>
        /// This is a username used for logging in
        /// </summary>
        [Required]
        public string Username { get; set; }
        /// <summary>
        /// This is a password used for logging in
        /// </summary>
        [Required]
        public string Password { get; set; }
        /// <summary>
        /// This attribute is the name of the user
        /// </summary>
        [Required]
        public string Name { get; set; }
        /// <summary>
        /// it gives info about the city of user
        /// </summary>
        [Required]
        public string City { get; set; }
        /// <summary>
        /// This is the email address of the user
        /// </summary>
        [Required]
        [EmailAddress]
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRoleMapping> UserRoleMappings { get; set; }
    }
}
