//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle()
        {
            this.Quotations = new HashSet<Quotation>();
            this.Sales = new HashSet<Sale>();
        }
    
        public int Id { get; set; }

        /// <summary>
        /// This is a serial number that is unique for each vehicle
        /// </summary>
        [Required]
        [Display(Name = "Serial Number")]
        public string SerialNumber { get; set; }

        /// <summary>
        /// This is the name of the company
        /// </summary>
        [Required]
        [Display(Name = "Company Name")]
        public string CompanyName { get; set; }

        /// <summary>
        /// This is the model name
        /// </summary>
        [Required]
        [Display(Name = "Model Name")]
        public string ModelName { get; set; }

        /// <summary>
        /// this is the date on which the vehicle was added to the collection
        /// </summary>
        [Required]
        [Display(Name = "Added on(Date)")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MMM/yyyy}")]
        public Nullable<System.DateTime> AddedOn { get; set; }

        /// <summary>
        /// This is the showroom price of the vehicle
        /// </summary>
        [Required]
        [Display(Name = "Showroom Price")]
        public string ShowroomPrice { get; set; }

        /// <summary>
        /// This is the description of the vehicle
        /// </summary>
        [Required]
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quotation> Quotations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sales { get; set; }
    }
}
