//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Visitor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Visitor()
        {
            this.Quotations = new HashSet<Quotation>();
        }
    
        public int Id { get; set; }

        /// <summary>
        /// This is the name of the vistor
        /// </summary>
        [Required]
        public string Name { get; set; }

        /// <summary>
        /// This is the date on which the visitor visited the showroom
        /// </summary>
        [Required]
        [Display(Name = "Date of Visit")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MMM/yyyy}")]
        public Nullable<System.DateTime> DateOfVisit { get; set; }
        /// <summary>
        /// This is the city in which the visitor resides
        /// </summary>
        [Required]
        public string City { get; set; }
        /// <summary>
        /// This is the Email id of the visitor
        /// </summary>
        [Required]
        [EmailAddress]
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quotation> Quotations { get; set; }
    }
}
